// Pure logic with no Arduino dependency, so `pio test -e native` can run it.
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

namespace gate {

// Seconds between the NTP epoch (1900) and the Unix epoch (1970). The 32-bit
// seconds field wraps in 2036, same as rally-server's NtpService.
const int64_t NTP_EPOCH_OFFSET_S = 2208988800LL;

inline uint32_t readBe32(const uint8_t *p) {
  return (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | p[3];
}

inline void writeBe32(uint8_t *p, uint32_t v) {
  p[0] = v >> 24;
  p[1] = v >> 16;
  p[2] = v >> 8;
  p[3] = v;
}

inline int64_t ntpToUnixUs(const uint8_t *p) {
  int64_t seconds = (int64_t)readBe32(p) - NTP_EPOCH_OFFSET_S;
  int64_t fractionUs = ((uint64_t)readBe32(p + 4) * 1000000ULL) >> 32;
  return seconds * 1000000 + fractionUs;
}

inline void unixUsToNtp(int64_t us, uint8_t *p) {
  writeBe32(p, (uint32_t)(us / 1000000 + NTP_EPOCH_OFFSET_S));
  writeBe32(p + 4, (uint32_t)(((uint64_t)(us % 1000000) << 32) / 1000000));
}

struct NtpSample {
  int64_t offsetUs;  // add to the local clock to get the server's
  int64_t delayUs;   // round trip, minus the server's own processing time
};

// RFC 5905: t1 request sent, t2 server received, t3 server replied, t4 reply
// received; t1/t4 on our clock, t2/t3 on the server's.
inline NtpSample ntpSample(int64_t t1, int64_t t2, int64_t t3, int64_t t4) {
  return {((t2 - t1) + (t3 - t4)) / 2, (t4 - t1) - (t3 - t2)};
}

// "2026-10-08T21:04:05.123Z", what the server parses as timestampGate/sentAt.
inline void isoTime(int64_t unixUs, char out[25]) {
  time_t seconds = (time_t)(unixUs / 1000000);
  struct tm t;
  gmtime_r(&seconds, &t);
  snprintf(out, 25, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ", t.tm_year + 1900,
           t.tm_mon + 1, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec,
           (int)(unixUs % 1000000 / 1000));
}

// Uppercase hex, no separators, in the order the tag reports. The registration
// desk has to enter exactly this, see docs/esp32-gate.md "Identifying a driver".
inline void uidHex(const uint8_t *uid, size_t len, char *out) {
  for (size_t i = 0; i < len; i++) snprintf(out + 2 * i, 3, "%02X", uid[i]);
  out[2 * len] = '\0';
}

inline void uuidV4(uint8_t b[16], char out[37]) {
  b[6] = (b[6] & 0x0F) | 0x40;
  b[8] = (b[8] & 0x3F) | 0x80;
  snprintf(out, 37,
           "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
           b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10],
           b[11], b[12], b[13], b[14], b[15]);
}

// A tap as buffered in flash, before it is known whether the clock is synced.
// Written raw, so a layout change bumps TAP_MAGIC rather than misreading taps
// a previous firmware left in the buffer.
const uint32_t TAP_MAGIC = 0x52475431;  // "RGT1"

struct Tap {
  uint32_t magic;
  char gateId[33];    // at the tap, so a rename never re-attributes buffered taps
  char eventId[37];
  char uid[21];       // up to 10-byte UIDs
  int64_t wallUs;     // 0 when the tap came before the first sync
  uint32_t bootId;    // boot counter at the tap, monoUs is only valid within it
  int64_t monoUs;     // esp_timer_get_time() at the tap
};

enum class TapTime { Known, NotYetSyncedWait, Unknown };

// A tap before the first sync gets its time back from the monotonic clock once
// synced. A reboot in between leaves no reference, so it is sent with the time
// of sending and flagged: presence proven, time of day not.
inline TapTime resolveTapTime(const Tap &tap, uint32_t bootId, bool synced,
                              int64_t nowWallUs, int64_t nowMonoUs,
                              int64_t *outUs) {
  if (tap.wallUs != 0) {
    *outUs = tap.wallUs;
    return TapTime::Known;
  }
  if (!synced) return TapTime::NotYetSyncedWait;
  if (tap.bootId == bootId) {
    *outUs = nowWallUs - (nowMonoUs - tap.monoUs);
    return TapTime::Known;
  }
  *outUs = nowWallUs;
  return TapTime::Unknown;
}

// Every value here is generated by the firmware (hex, UUID, ISO time) or a
// gate id restricted to [A-Z0-9_], so nothing needs JSON escaping.
inline int detectionJson(const Tap &tap, int64_t timeUs, bool timeUnknown,
                         char *out, size_t size) {
  char iso[25];
  isoTime(timeUs, iso);
  return snprintf(out, size,
                  "{\"eventId\":\"%s\",\"gateId\":\"%s\",\"transponderId\":\"%s\","
                  "\"transponderKind\":\"NFC\",\"timestampGate\":\"%s\","
                  "\"source\":\"nfc\"%s}",
                  tap.eventId, tap.gateId, tap.uid, iso,
                  timeUnknown ? ",\"metadata\":{\"timeUnknown\":true}" : "");
}

// Gate ids are matched verbatim by the server and used in MQTT topics, so the
// same alphabet as the Pi installer's (CLUB_START_WP1): A-Z, 0-9, underscore.
inline bool validGateId(const char *id) {
  size_t len = strlen(id);
  if (len == 0 || len > 32) return false;
  for (size_t i = 0; i < len; i++) {
    char c = id[i];
    if (!((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')) return false;
  }
  return true;
}

// For the strings a marshal typed (SSID, server host) on the status page.
inline void jsonEscape(const char *in, char *out, size_t size) {
  size_t o = 0;
  for (; *in && o + 7 < size; in++) {
    unsigned char c = *in;
    if (c == '"' || c == '\\') {
      out[o++] = '\\';
      out[o++] = c;
    } else if (c < 0x20) {
      o += snprintf(out + o, size - o, "\\u%04x", c);
    } else {
      out[o++] = c;
    }
  }
  out[o] = '\0';
}

}  // namespace gate

