# Runs before every firmware build: stamps the version and embeds the status
# page, gzipped, so one OTA image always carries its own page.
import gzip
import subprocess
from pathlib import Path

Import("env")

# Same stamp as packages/shared/write-version.js, so the dashboard's version
# mismatch check compares like with like.
try:
    version = subprocess.check_output(
        ["git", "describe", "--tags", "--always", "--dirty"], text=True
    ).strip()
except Exception:
    version = "unknown"
env.Append(CPPDEFINES=[("FIRMWARE_VERSION", env.StringifyMacro(version))])

root = Path(env.subst("$PROJECT_DIR"))
page = gzip.compress((root / "web" / "index.html").read_bytes(), 9, mtime=0)
body = ",".join(str(b) for b in page)
(root / "src" / "page.h").write_text(
    "// Generated by prebuild.py from web/index.html. Do not edit.\n"
    "#pragma once\n#include <stdint.h>\n"
    f"static const uint8_t PAGE_GZ[] = {{{body}}};\n"
)
